# Generated by Django 4.2.4 on 2023-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_punejobs_address_alter_punejobs_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.TextField(),
        ),
    ]
